Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wg25r/turbo/VSF/scripts/paper_demo.py", line 22, in <module>
    subprocess.run(['python3', 'wan_nag.py', '--prompt', prompts[i], '--neg_prompt', neg_prompts[i], '--video_id', str(i)])
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wg25r/turbo/VSF/scripts/paper_demo.py", line 22, in <module>
    subprocess.run(['python3', 'wan_nag.py', '--prompt', prompts[i], '--neg_prompt', neg_prompts[i], '--video_id', str(i)])
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x78ef34b08550>
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/service/service_connection.py", line 54, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/service/service_connection.py", line 182, in teardown
    self._router.join()
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
