2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_setup.py:_flush():80] Configure stats pid to 1976423
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_setup.py:_flush():80] Loading settings from /home/wg25r/.config/wandb/settings
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_setup.py:_flush():80] Loading settings from /home/wg25r/turbo/VSF/scripts/wandb/settings
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/wg25r/turbo/VSF/scripts/wandb/run-20250722_225209-1b9lv8t7/logs/debug.log
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/wg25r/turbo/VSF/scripts/wandb/run-20250722_225209-1b9lv8t7/logs/debug-internal.log
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_init.py:init():830] calling init triggers
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-22 22:52:09,456 INFO    MainThread:1976423 [wandb_init.py:init():871] starting backend
2025-07-22 22:52:09,666 INFO    MainThread:1976423 [wandb_init.py:init():874] sending inform_init request
2025-07-22 22:52:09,672 INFO    MainThread:1976423 [wandb_init.py:init():882] backend started and connected
2025-07-22 22:52:09,673 INFO    MainThread:1976423 [wandb_init.py:init():953] updated telemetry
2025-07-22 22:52:09,683 INFO    MainThread:1976423 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-22 22:52:10,134 INFO    MainThread:1976423 [wandb_init.py:init():1029] starting run threads in backend
2025-07-22 22:52:10,536 INFO    MainThread:1976423 [wandb_run.py:_console_start():2458] atexit reg
2025-07-22 22:52:10,537 INFO    MainThread:1976423 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-22 22:52:10,537 INFO    MainThread:1976423 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-22 22:52:10,537 INFO    MainThread:1976423 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-22 22:52:10,538 INFO    MainThread:1976423 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-22 22:54:17,720 INFO    MsgRouterThr:1976423 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-22 22:54:18,013 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,017 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,018 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,019 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,020 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,021 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,022 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,023 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,024 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,025 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,026 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,026 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,027 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,028 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,029 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,030 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,031 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,032 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,033 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,034 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,035 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,036 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,038 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,039 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,040 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,040 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,041 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,042 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-22 22:54:18,043 ERROR   MainThread:1976423 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/wg25r/miniconda/envs/neg/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
